clear

echo "                                                                         "
echo "                                                                         "
echo "                                                                         "
echo "                                     ▄▄▄      ▓█████▄  ███▄ ▄███▓ ▄▄▄     ▄▄▄█████▓"
echo "                                    ▒████▄    ▒██▀ ██▌▓██▒▀█▀ ██▒▒████▄   ▓  ██▒ ▓▒"
echo "                                    ▒██  ▀█▄  ░██   █▌▓██    ▓██░▒██  ▀█▄ ▒ ▓██░ ▒░"
echo "                                    ░██▄▄▄▄██ ░▓█▄   ▌▒██    ▒██ ░██▄▄▄▄██░ ▓██▓ ░ "
echo "                                     ▓█   ▓██▒░▒████▓ ▒██▒   ░██▒ ▓█   ▓██▒ ▒██▒ ░ "
echo "                                     ▒▒   ▓▒█░ ▒▒▓  ▒ ░ ▒░   ░  ░ ▒▒   ▓▒█░ ▒ ░░ "
echo "                                     ▒   ▒▒ ░ ░ ▒  ▒ ░  ░      ░  ▒   ▒▒ ░   ░  "
echo "                                    ░   ▒    ░ ░  ░ ░      ░     ░   ▒    ░   "
echo "                                        ░  ░   ░           ░         ░  ░   "
echo "                                             ░     "





python3 /home/ubuntu/Desktop/proxit/BTC.py &
python3 /home/ubuntu/Desktop/proxit/ETH.py &
python3 /home/ubuntu/Desktop/proxit/BNB.py &
python3 /home/ubuntu/Desktop/proxit/XRP.py &
python3 /home/ubuntu/Desktop/proxit/ADA.py &
python3 /home/ubuntu/Desktop/proxit/SOL.py &
python3 /home/ubuntu/Desktop/proxit/DOGE.py &
python3 /home/ubuntu/Desktop/proxit/MATIC.py &
python3 /home/ubuntu/Desktop/proxit/DOT.py &
python3 /home/ubuntu/Desktop/proxit/DAI.py &
python3 /home/ubuntu/Desktop/proxit/SHIB.py &
python3 /home/ubuntu/Desktop/proxit/TRX.py &
python3 /home/ubuntu/Desktop/proxit/AVAX.py &
python3 /home/ubuntu/Desktop/proxit/UNI.py &
python3 /home/ubuntu/Desktop/proxit/WBTC.py &
python3 /home/ubuntu/Desktop/proxit/LEO.py &
python3 /home/ubuntu/Desktop/proxit/LTC.py &
python3 /home/ubuntu/Desktop/proxit/ATOM.py &
python3 /home/ubuntu/Desktop/proxit/LINK.py &
python3 /home/ubuntu/Desktop/proxit/ETC.py &
python3 /home/ubuntu/Desktop/proxit/XLM.py &
python3 /home/ubuntu/Desktop/proxit/FTT.py &
python3 /home/ubuntu/Desktop/proxit/NEAR.py &
python3 /home/ubuntu/Desktop/proxit/CRO.py &
python3 /home/ubuntu/Desktop/proxit/XMR.py &
python3 /home/ubuntu/Desktop/proxit/ALGO.py &
python3 /home/ubuntu/Desktop/proxit/BCH.py &
python3 /home/ubuntu/Desktop/proxit/LUNC.py &
python3 /home/ubuntu/Desktop/proxit/QNT.py &
python3 /home/ubuntu/Desktop/proxit/FLOW.py &
python3 /home/ubuntu/Desktop/proxit/VET.py &
python3 /home/ubuntu/Desktop/proxit/TON.py &
python3 /home/ubuntu/Desktop/proxit/APE.py &
python3 /home/ubuntu/Desktop/proxit/FIL.py &
python3 /home/ubuntu/Desktop/proxit/ICP.py &
python3 /home/ubuntu/Desktop/proxit/HBAR.py &
python3 /home/ubuntu/Desktop/proxit/EGLD.py &
python3 /home/ubuntu/Desktop/proxit/XTZ.py &
python3 /home/ubuntu/Desktop/proxit/MANA.py &
python3 /home/ubuntu/Desktop/proxit/SAND.py &
python3 /home/ubuntu/Desktop/proxit/CHZ.py &
python3 /home/ubuntu/Desktop/proxit/EOS.py &
python3 /home/ubuntu/Desktop/proxit/AAVE.py &
python3 /home/ubuntu/Desktop/proxit/THETA.py &
python3 /home/ubuntu/Desktop/proxit/AXS.py &
python3 /home/ubuntu/Desktop/proxit/USDP.py &
python3 /home/ubuntu/Desktop/proxit/OKB.py &
python3 /home/ubuntu/Desktop/proxit/BSV.py &
python3 /home/ubuntu/Desktop/proxit/TUSD.py &
python3 /home/ubuntu/Desktop/proxit/MKR.py &
python3 /home/ubuntu/Desktop/proxit/KCS.py &
python3 /home/ubuntu/Desktop/proxit/ZEC.py &
python3 /home/ubuntu/Desktop/proxit/USDD.py &
python3 /home/ubuntu/Desktop/proxit/HT.py &
python3 /home/ubuntu/Desktop/proxit/XEC.py &
python3 /home/ubuntu/Desktop/proxit/MIOTA.py &
python3 /home/ubuntu/Desktop/proxit/BTT.py &
python3 /home/ubuntu/Desktop/proxit/USDN.py &
python3 /home/ubuntu/Desktop/proxit/CAKE.py &
python3 /home/ubuntu/Desktop/proxit/GRT.py &
python3 /home/ubuntu/Desktop/proxit/NEO.py &
python3 /home/ubuntu/Desktop/proxit/HNT.py &
python3 /home/ubuntu/Desktop/proxit/KLAY.py &
python3 /home/ubuntu/Desktop/proxit/FTM.py &
python3 /home/ubuntu/Desktop/proxit/PAXG.py &
python3 /home/ubuntu/Desktop/proxit/SNX.py &
python3 /home/ubuntu/Desktop/proxit/RUNE.py &
python3 /home/ubuntu/Desktop/proxit/NEXO.py &
python3 /home/ubuntu/Desktop/proxit/GT.py &
python3 /home/ubuntu/Desktop/proxit/DASH.py &
python3 /home/ubuntu/Desktop/proxit/CRV.py &
python3 /home/ubuntu/Desktop/proxit/BAT.py &
python3 /home/ubuntu/Desktop/proxit/ENJ.py &
python3 /home/ubuntu/Desktop/proxit/LDO.py &
python3 /home/ubuntu/Desktop/proxit/STX.py &
python3 /home/ubuntu/Desktop/proxit/KAVA.py &
python3 /home/ubuntu/Desktop/proxit/COMP.py &
python3 /home/ubuntu/Desktop/proxit/ZIL.py &
python3 /home/ubuntu/Desktop/proxit/FEI.py &
python3 /home/ubuntu/Desktop/proxit/RVN.py &
python3 /home/ubuntu/Desktop/proxit/MINA.py &
python3 /home/ubuntu/Desktop/proxit/WAVES.py &
python3 /home/ubuntu/Desktop/proxit/XDC.py &
python3 /home/ubuntu/Desktop/proxit/USDTC.py &
python3 /home/ubuntu/Desktop/proxit/GMT.py &
python3 /home/ubuntu/Desktop/proxit/TWT.py &
python3 /home/ubuntu/Desktop/proxit/LRC.py &
python3 /home/ubuntu/Desktop/proxit/DCR.py &
python3 /home/ubuntu/Desktop/proxit/CVX.py &
python3 /home/ubuntu/Desktop/proxit/CSPR.py &
python3 /home/ubuntu/Desktop/proxit/XEM.py &
python3 /home/ubuntu/Desktop/proxit/KSM.py &
python3 /home/ubuntu/Desktop/proxit/CELO.py &
python3 /home/ubuntu/Desktop/proxit/BTG.py &
python3 /home/ubuntu/Desktop/proxit/ENS.py &
python3 /home/ubuntu/Desktop/proxit/1INCH.py &
python3 /home/ubuntu/Desktop/proxit/HOT.py &
python3 /home/ubuntu/Desktop/proxit/LUNA.py &
python3 /home/ubuntu/Desktop/proxit/RSR.py &
python3 /home/ubuntu/Desktop/proxit/BNX.py &
python3 /home/ubuntu/Desktop/proxit/GUSD.py &
python3 /home/ubuntu/Desktop/proxit/ROSE.py &
python3 /home/ubuntu/Desktop/proxit/YFI.py &
python3 /home/ubuntu/Desktop/proxit/QTUM.py &
python3 /home/ubuntu/Desktop/proxit/AR.py &
python3 /home/ubuntu/Desktop/proxit/ANKR.py &
python3 /home/ubuntu/Desktop/proxit/GNO.py &
python3 /home/ubuntu/Desktop/proxit/GALA.py &
python3 /home/ubuntu/Desktop/proxit/TFUEL.py &
python3 /home/ubuntu/Desktop/proxit/KDA.py &
python3 /home/ubuntu/Desktop/proxit/IOTX.py &
python3 /home/ubuntu/Desktop/proxit/GLM.py &
python3 /home/ubuntu/Desktop/proxit/BTRST.py &
python3 /home/ubuntu/Desktop/proxit/JST.py &
python3 /home/ubuntu/Desktop/proxit/CEL.py &
python3 /home/ubuntu/Desktop/proxit/POLY.py &
python3 /home/ubuntu/Desktop/proxit/ONE.py &
python3 /home/ubuntu/Desktop/proxit/HIVE.py &
python3 /home/ubuntu/Desktop/proxit/OMG.py &
python3 /home/ubuntu/Desktop/proxit/LPT.py &
python3 /home/ubuntu/Desktop/proxit/ZRX.py &
python3 /home/ubuntu/Desktop/proxit/BAL.py &
python3 /home/ubuntu/Desktop/proxit/FLUX.py &
python3 /home/ubuntu/Desktop/proxit/IOST.py &
python3 /home/ubuntu/Desktop/proxit/ICX.py &
python3 /home/ubuntu/Desktop/proxit/BORA.py &
python3 /home/ubuntu/Desktop/proxit/AMP.py &
python3 /home/ubuntu/Desktop/proxit/XYM.py &
python3 /home/ubuntu/Desktop/proxit/SRM.py &
python3 /home/ubuntu/Desktop/proxit/KNC.py &
python3 /home/ubuntu/Desktop/proxit/ONT.py &
python3 /home/ubuntu/Desktop/proxit/OP.py &
python3 /home/ubuntu/Desktop/proxit/GLMR.py &
python3 /home/ubuntu/Desktop/proxit/CHSB.py &
python3 /home/ubuntu/Desktop/proxit/STORJ.py &
python3 /home/ubuntu/Desktop/proxit/WAXP.py &
python3 /home/ubuntu/Desktop/proxit/SC.py &
python3 /home/ubuntu/Desktop/proxit/WOO.py &
python3 /home/ubuntu/Desktop/proxit/ZEN.py &
python3 /home/ubuntu/Desktop/proxit/XCH.py &
python3 /home/ubuntu/Desktop/proxit/SXP.py &
python3 /home/ubuntu/Desktop/proxit/SUSHI.py &
python3 /home/ubuntu/Desktop/proxit/IMX.py &
python3 /home/ubuntu/Desktop/proxit/MXC.py &
python3 /home/ubuntu/Desktop/proxit/AUDIO.py &
python3 /home/ubuntu/Desktop/proxit/NFT.py &
python3 /home/ubuntu/Desktop/proxit/UMA.py &
python3 /home/ubuntu/Desktop/proxit/PLA.py &
python3 /home/ubuntu/Desktop/proxit/SKL.py &
python3 /home/ubuntu/Desktop/proxit/ABBC.py &
python3 /home/ubuntu/Desktop/proxit/SCRT.py &
python3 /home/ubuntu/Desktop/proxit/SLP.py &
python3 /home/ubuntu/Desktop/proxit/DGB.py &
python3 /home/ubuntu/Desktop/proxit/ELON.py &
python3 /home/ubuntu/Desktop/proxit/INJ.py &
python3 /home/ubuntu/Desktop/proxit/VGX.py &
python3 /home/ubuntu/Desktop/proxit/CKB.py &
python3 /home/ubuntu/Desktop/proxit/CVC.py &
python3 /home/ubuntu/Desktop/proxit/LSK.py &
python3 /home/ubuntu/Desktop/proxit/VLX.py &
python3 /home/ubuntu/Desktop/proxit/PUNDIX.py &
python3 /home/ubuntu/Desktop/proxit/COTI.py &
python3 /home/ubuntu/Desktop/proxit/KEEP.py &
python3 /home/ubuntu/Desktop/proxit/DAO.py &
python3 /home/ubuntu/Desktop/proxit/REN.py &
python3 /home/ubuntu/Desktop/proxit/MED.py &
python3 /home/ubuntu/Desktop/proxit/RNDR.py &
python3 /home/ubuntu/Desktop/proxit/CEEK.py &
python3 /home/ubuntu/Desktop/proxit/REEF.py &
python3 /home/ubuntu/Desktop/proxit/EWT.py &
python3 /home/ubuntu/Desktop/proxit/PEOPLE.py &
python3 /home/ubuntu/Desktop/proxit/BTCST.py &
python3 /home/ubuntu/Desktop/proxit/WIN.py &
python3 /home/ubuntu/Desktop/proxit/NU.py &
python3 /home/ubuntu/Desktop/proxit/CELR.py &
python3 /home/ubuntu/Desktop/proxit/SYS.py &
python3 /home/ubuntu/Desktop/proxit/ONG.py &
python3 /home/ubuntu/Desktop/proxit/XNO.py &
python3 /home/ubuntu/Desktop/proxit/REQ.py &
python3 /home/ubuntu/Desktop/proxit/DAG.py &
python3 /home/ubuntu/Desktop/proxit/ORBS.py &
python3 /home/ubuntu/Desktop/proxit/SPELL.py &
python3 /home/ubuntu/Desktop/proxit/RLC.py &
python3 /home/ubuntu/Desktop/proxit/OCEAN.py &
python3 /home/ubuntu/Desktop/proxit/API3.py &
python3 /home/ubuntu/Desktop/proxit/SNT.py &
python3 /home/ubuntu/Desktop/proxit/TRIBE.py &
python3 /home/ubuntu/Desktop/proxit/ARDR.py &
python3 /home/ubuntu/Desktop/proxit/PYR.py &
python3 /home/ubuntu/Desktop/proxit/FX.py &
python3 /home/ubuntu/Desktop/proxit/UOS.py &
python3 /home/ubuntu/Desktop/proxit/POWER.py &
python3 /home/ubuntu/Desktop/proxit/ACA.py &
python3 /home/ubuntu/Desktop/proxit/PROM.py &
python3 /home/ubuntu/Desktop/proxit/DENT.py &
python3 /home/ubuntu/Desktop/proxit/CHR.py &
python3 /home/ubuntu/Desktop/proxit/MX.py &
python3 /home/ubuntu/Desktop/proxit/%launcher%


